
  
spring:  
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_yhxwfx
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  typeAliasesPackage: com.thunisoft.ipareainfo.bean  
server: 
  port: 8080
  context-path: /ipinfo
constant: 
  servicename: ipinfo_service
  #更新ip信息的开关
  switchupdatetask: true
  iptaobaourl: http://ip.taobao.com/service/getIpInfo.php?ip=
#更新ip信息的定时
scheduler:
  updatetaskcron: 0 0 * * * ?